### ISSUE TITLE
Middleware for Caching Study Spot Location Data

### ISSUE THREAD

**Issue by daviskeene** [IllinoisLabs/spots-api#4]
## Description

When a user creates a Study Spot, we should pull from the Google Business Profiles API their reviews / hours of operation / anything else and cache it into a `GoogleBusinessModel` document. This will improve performance and save API calls for the future.

## TODOS
- [ ] Finish #3 to have lightweight wrapper for APIs ready.
- [ ] Determine what Google Business and Maps metrics we need to collect for study spots.
- [ ] Create `GoogleBusinessModel` class in `models.py` that corresponds to a new MongoDB collection.
